# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Air Colors
email: benoitvallon@gmail.com
author: Benoit VALLON
description: Air Colors is an App that allows you to know about your Air Quality environment.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/air-colors
  - title: github
    url: https://github.com/air-colors

google_analytics: UA-64483496-2
google:
  webmaster-tools: jshE2qqTg-J58-f9lXXmMFvUkZqqjAxltrnJu7ZODh0
